modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/palmmc/AnalogAudio/issues"

[[mods]]

modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
mixins=["analogaudio.mixins.json"]
logoFile="icon.png"
authors="palm1"
credits="${mod_credits}"
description='''
Bring the warm comfort of analog audio mediums to your world!
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="sable"
    type="optional"
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="simulated"
    type="optional"
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="voicechat"
    type="optional"
    versionRange="[1.21.1-2.6.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="optional"
    versionRange="[0.6.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="yet_another_config_lib_v3"
    type="optional"
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"